# Generated by Django 5.0.7 on 2024-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_lesson_preview_image_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(default='lms/courses/previews/defImage.jpg', upload_to='lms/courses/previews/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview_image',
            field=models.ImageField(default='lms/lessons/previews/defImage.jpg', upload_to='lms/lessons/previews/'),
        ),
    ]
